# ==============================================================================
# Google Cloud GKE Vault ServiceAccounts & Workload Identity
# ==============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: products-service
  namespace: prod
  annotations:
    iam.gke.io/gcp-service-account: "products-service@msa-production-project.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-service
  namespace: prod
  annotations:
    iam.gke.io/gcp-service-account: "orders-service@msa-production-project.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cosmo-router
  namespace: prod
  annotations:
    iam.gke.io/gcp-service-account: "cosmo-router@msa-production-project.iam.gserviceaccount.com"
