{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "orders-service.fullname" . }}-servicemonitor
  labels:
    app: {{ include "orders-service.fullname" . }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "orders-service.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: 10s
      honorLabels: true
{{- end }}