apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-service.fullname" . }}
  labels:
    {{- include "orders-service.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: orders-service
