{{- if and .Values.keda .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "apollo-router.fullname" . }}-scaler
  labels:
    {{- include "apollo-router.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "apollo-router.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount | default 1 }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount | default 3 }}
  {{- if and .Values.keda.minReplicaCount (eq (int .Values.keda.minReplicaCount) 0) }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default 300 }}
  pollingInterval: {{ .Values.keda.pollingInterval | default 15 }}
  {{- end }}
  triggers:
    {{- if and .Values.keda.prometheus .Values.keda.prometheus.enabled }}
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.keda.prometheus.serverAddress | default "http://kube-prometheus-kube-prome-prometheus.observability.svc.cluster.local:9090" | quote }}
        metricName: {{ .Values.keda.prometheus.metricName | default "apollo_router_requests_per_second" | quote }}
        query: {{ .Values.keda.prometheus.query | default "sum(rate(http_server_request_duration_seconds_count{otel_scope_name='apollo/router'}[1m]))" | quote }}
        threshold: {{ .Values.keda.prometheus.threshold | default "100" | quote }}
    {{- end }}
    {{- if and .Values.keda.cpu .Values.keda.cpu.enabled }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: {{ .Values.keda.cpu.targetUtilizationPercentage | default "70" | quote }}
    {{- end }}
    {{- if and .Values.keda.memory .Values.keda.memory.enabled }}
    - type: memory
      metricType: Utilization
      metadata:
        value: {{ .Values.keda.memory.targetUtilizationPercentage | default "80" | quote }}
    {{- end }}
{{- end }}
