name: MSA-Frontend-SPA-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - frontend/**
      - helm/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/**

variables:
  - name: AZURE_SERVICE_CONNECTION
    value: 'azure-service-connection'
  - name: AZURE_RG
    value: 'msa-azure-prod-rg'
  - name: AKS_CLUSTER_NAME
    value: 'msa-azure-prod-aks'
  - name: ACR_NAME
    value: 'msaazureprodacr'

stages:
  - template: ../templates/azure-pipelines.yml
    parameters:
      serviceName: 'frontend'
      serviceDir: 'frontend'
      serviceType: 'react'
      servicePort: 80
