name: Novashop-Frontend-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include: [develop, release/*, main, master]
  paths:
    include:
      - frontend/**
      - helm/**
      - devsecops/**
      - azure-devops/pipelines/frontend.yml
      - azure-devops/templates/**

pr:
  branches:
    include: [develop, release/*, main, master]
  paths:
    include:
      - frontend/**
      - helm/**
      - devsecops/**
      - azure-devops/pipelines/frontend.yml
      - azure-devops/templates/**

variables:
  - template: ../templates/gates.yml

pool:
  vmImage: ubuntu-latest

stages:
  - template: ../templates/app-stages.yml
    parameters:
      serviceName: frontend
      serviceDir: frontend
      serviceType: react
      servicePort: 80
      serviceConnection: azure-service-connection
      acrNameDev: msaazuredevacr
      acrNameStaging: msaazurestagingacr
      acrNameProd: msaazureprodacr
      namePrefix: msa-azure
