name: MSA-Notification-Service-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include: [develop, release/*, main, master]
  paths:
    include:
      - notification-service/**
      - helm/**
      - devsecops/**
      - azure-devops/pipelines/notification-service.yml
      - azure-devops/templates/**

pr:
  branches:
    include: [develop, release/*, main, master]
  paths:
    include:
      - notification-service/**
      - helm/**
      - devsecops/**
      - azure-devops/pipelines/notification-service.yml
      - azure-devops/templates/**

variables:
  - template: ../templates/gates.yml

pool:
  vmImage: ubuntu-latest

stages:
  - template: ../templates/app-stages.yml
    parameters:
      serviceName: notification-service
      serviceDir: notification-service
      serviceType: spring-boot
      servicePort: 8002
      serviceConnection: azure-service-connection
      acrNameDev: msaazuredevacr
      acrNameStaging: msaazurestagingacr
      acrNameProd: msaazureprodacr
      namePrefix: msa-azure
