name: MSA-Products-Service-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include: [develop, release/*, main, master]
  paths:
    include:
      - products-service/**
      - helm/**
      - devsecops/**
      - azure-devops/pipelines/products-service.yml
      - azure-devops/templates/**

pr:
  branches:
    include: [develop, release/*, main, master]
  paths:
    include:
      - products-service/**
      - helm/**
      - devsecops/**
      - azure-devops/pipelines/products-service.yml
      - azure-devops/templates/**

variables:
  - template: ../templates/gates.yml

pool:
  vmImage: ubuntu-latest

stages:
  - template: ../templates/app-stages.yml
    parameters:
      serviceName: products-service
      serviceDir: products-service
      serviceType: spring-boot
      servicePort: 8004
      serviceConnection: azure-service-connection
      acrNameDev: msaazuredevacr
      acrNameStaging: msaazurestagingacr
      acrNameProd: msaazureprodacr
      namePrefix: msa-azure
      canaryEnabled: false
      canaryVirtualServicePath: ''
