apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microservices-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway # Uses Istio default Ingress Gateway proxy
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservices-edge-routes
  namespace: dev
spec:
  hosts:
    - "*"
  gateways:
    - microservices-gateway
  http:
    # 1. GraphQL Supergraph requests -> Routed to Cosmo Router v2
    - match:
        - uri:
            prefix: /graphql
        - uri:
            exact: /health
      route:
        - destination:
            host: cosmo-router.dev.svc.cluster.local
            port:
              number: 8080

    # 1.1 SSE Real-Time Notifications -> Routed to Notification Service
    - match:
        - uri:
            prefix: /api/notifications/
      route:
        - destination:
            host: notification-service.dev.svc.cluster.local
            port:
              number: 8002

    # 1.2 Telemetry Funnel Events -> Routed to Orders Service
    - match:
        - uri:
            prefix: /api/order/funnel
      route:
        - destination:
            host: orders-service.dev.svc.cluster.local
            port:
              number: 8003

    # 2. Keycloak Auth requests -> Routed to Keycloak
    - match:
        - uri:
            prefix: /realms/
        - uri:
            prefix: /resources/
        - uri:
            prefix: /admin/
        - uri:
            prefix: /js/
      route:
        - destination:
            host: keycloak.auth.svc.cluster.local
            port:
              number: 8181

    # 3. Default / Root -> Routed to React 19 SPA Storefront
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend.dev.svc.cluster.local
            port:
              number: 80
