apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sTrustedRegistries
metadata:
  name: enforce-trusted-registry
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces:
      - "staging"
      - "prod"
      - "ecommerce"
  parameters:
    registries:
      - "georgegxx/"
      - "docker.io/georgegxx/"
      - "localhost"
      - "10.0."
      - "192.168."
      - "gcr.io/distroless"
