# Minikube values pointing to the local Harbor registry
global:
  environment: local
  harborRegistry: harbor.local:30002/microservices

api-gateway:
  image:
    repository: harbor.local:30002/microservices/msa-api-gateway
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

inventory-service:
  image:
    repository: harbor.local:30002/microservices/msa-inventory-service
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

notification-service:
  image:
    repository: harbor.local:30002/microservices/msa-notification-service
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

orders-service:
  image:
    repository: harbor.local:30002/microservices/msa-orders-service
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

products-service:
  image:
    repository: harbor.local:30002/microservices/msa-products-service
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
