apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmo-router.fullname" . }}
  labels:
    {{- include "cosmo-router.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-router
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
    - name: http-metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
      protocol: TCP
  selector:
    app: cosmo-router
