apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: opencost-cloud
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            finops.opencost.io/enabled: "true"
  template:
    metadata:
      name: opencost-{{ .name }}
    spec:
      project: microservices-architecture
      sources:
        - repoURL: https://opencost.github.io/opencost-helm-chart
          chart: opencost
          targetRevision: 2.5.32
          helm:
            releaseName: opencost
            valueFiles:
              - $values/helm/values/opencost-cloud.yaml
            parameters:
              - name: clusterName
                value: cluster.local
              - name: opencost.exporter.defaultClusterId
                value: '{{ .name }}'
        - repoURL: https://github.com/GeorgeGxx/microservices-architecture.git
          targetRevision: '{{ index .metadata.labels "git-branch" }}'
          ref: values
      destination:
        server: '{{ .server }}'
        namespace: opencost
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
