apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: microservices-architecture
  source:
    repoURL: https://github.com/georgegxx/microservices-architecture.git
    targetRevision: develop
    path: helm/microservices-umbrella
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
