apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: microservices-architecture
  source:
    repoURL: https://github.com/GeorgeGxx/microservices-architecture.git
    targetRevision: main
    path: helm/microservices-umbrella
    helm:
      valueFiles:
        - values.yaml
        - ../values/values-eks-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: microservices-secrets
      jsonPointers:
        - /data
        - /stringData
    - group: "monitoring.coreos.com"
      kind: ServiceMonitor
      jsonPointers:
        - /spec/endpoints
