apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservices-architecture
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Enterprise Microservices Architecture on Google Kubernetes Engine (GKE)
  sourceRepos:
    - '*'
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
