FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    HOME=/tmp

WORKDIR /app
RUN pip install --no-cache-dir "kafka-python==2.3.2" "python-snappy==0.7.3"
COPY capture_orders.py ./

ENTRYPOINT ["python", "/app/capture_orders.py", "--engine", "python"]
