apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-custom
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus-DS
        uid: prometheus-ds
        type: prometheus
        access: proxy
        url: http://kube-prometheus-kube-prome-prometheus.observability.svc.cluster.local:9090
        isDefault: false
        jsonData:
          httpMethod: POST
          timeInterval: 15s
      - name: Loki
        uid: loki-ds
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        isDefault: false
        jsonData:
          maxLines: 1000
