apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: data
  labels:
    app: postgres-exporter
spec:
  ports:
    - name: http-metrics
      port: 9187
      targetPort: 9187
  selector:
    app: postgres-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: data
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.20.1
          env:
            - name: DATA_SOURCE_URI
              value: "db-orders:5432/ms_orders?sslmode=disable"
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: POSTGRES_USER
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - name: http-metrics
              containerPort: 9187
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
              ephemeral-storage: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
              ephemeral-storage: "128Mi"
