apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: ecommerce
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-role
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: ecommerce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ecommerce
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'spring-microservices'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - ecommerce
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: (api-gateway|products-service|inventory-service|orders-service|notification-service)
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: (api-gateway|products-service|inventory-service|orders-service|notification-service)
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_container_port_number]
            regex: (.+);(.+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: __metrics_path__
            regex: api-gateway
            replacement: /actuator/prometheus
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: __metrics_path__
            regex: inventory-service
            replacement: /actuator/inventory/prometheus
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: __metrics_path__
            regex: notification-service
            replacement: /actuator/notification/prometheus
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: __metrics_path__
            regex: orders-service
            replacement: /actuator/orders/prometheus
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: __metrics_path__
            regex: products-service
            replacement: /actuator/products/prometheus
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: job
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance

      - job_name: 'envoy-stats'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - ecommerce
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: istio-proxy
          - source_labels: [__meta_kubernetes_pod_ip]
            replacement: $1:15090
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: job
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance

      - job_name: 'istiod'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - istio-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: istiod;http-monitoring

      - job_name: 'vault'
        metrics_path: /v1/sys/metrics
        params:
          format: ['prometheus']
        bearer_token: 'root'
        static_configs:
          - targets: ['vault.vault.svc.cluster.local:8200']
        relabel_configs:
          - target_label: service
            replacement: vault
          - target_label: job
            replacement: vault
          - target_label: app
            replacement: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      automountServiceAccountToken: true
      containers:
        - name: prometheus
          image: prom/prometheus:v3.13.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "1500m"
              memory: "1024Mi"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: http-prom
      port: 9090
      targetPort: 9090
      nodePort: 30090
