apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microservices-external-secret
  namespace: dev
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: microservices-secrets
    creationPolicy: Merge
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/application
        property: spring.datasource.password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/data/application
        property: spring.datasource.username
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: secret/data/cosmo-router
        property: keycloak.client-secret
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/data/application
        property: jwt.secret
