apiVersion: v2
name: microservices-umbrella
description: Umbrella chart deploying Cosmo Router, the frontend, and 4 business microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
annotations:
  org.opencontainers.image.source: "https://github.com/GeorgeGxx/microservices-architecture"
  microservices-architecture.io/helm-oci-repository: "oci://ghcr.io/georgegxx/helm-charts/microservices-umbrella"
dependencies:
  - name: cosmo-router
    version: "2.0.0"
    repository: "file://../charts/cosmo-router"
  - name: inventory-service
    version: "1.0.0"
    repository: "file://../charts/inventory-service"
  - name: notification-service
    version: "1.0.0"
    repository: "file://../charts/notification-service"
  - name: orders-service
    version: "1.0.0"
    repository: "file://../charts/orders-service"
  - name: products-service
    version: "1.0.0"
    repository: "file://../charts/products-service"
