#!/usr/bin/env python3
"""
gke-disk-cleanup.py

Enterprise GCP Persistent Disk Snapshot & FinOps Lifecycle Manager.
Audits and purges expired Google Cloud Persistent Disk snapshots generated by
GKE stateful workloads (Kafka, PostgreSQL, Redis) to optimize cloud storage costs.

Author  : GeorgeGxx/DevOps
Version : v2.0.0

Usage:
  python gke-disk-cleanup.py --project-id msa-gcp-prod --retention-days 14
  python gke-disk-cleanup.py --project-id msa-gcp-prod --dry-run
"""

import argparse
from datetime import datetime, timezone
import os
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

try:
    from google.cloud import compute_v1
    from google.api_core.exceptions import GoogleAPICallError
except ImportError:
    print("❌ Error: google-cloud-compute is not installed. Run: pip install google-cloud-compute", file=sys.stderr)
    sys.exit(1)


def cleanup_snapshots(project_id: str, retention_days: int = 30, dry_run: bool = False, filter_prefix: str = ""):
    print(f"☁️  GCP Project ID  : {project_id}")
    print(f"⏳ Retention Period: {retention_days} days")
    if filter_prefix:
        print(f"🔍 Filter Prefix   : {filter_prefix}")

    try:
        snapshot_client = compute_v1.SnapshotsClient()
        request = compute_v1.ListSnapshotsRequest(project=project_id)
        snapshots = list(snapshot_client.list(request=request))
    except GoogleAPICallError as e:
        print(f"❌ Failed to list snapshots in project '{project_id}': {e}", file=sys.stderr)
        sys.exit(1)

    print(f"📦 Total snapshots found: {len(snapshots)}")

    now = datetime.now(timezone.utc)
    deleted_count = 0
    retained_count = 0
    total_freed_gb = 0

    for snap in snapshots:
        name = snap.name
        if filter_prefix and not name.startswith(filter_prefix):
            continue

        if not snap.creation_timestamp:
            continue

        # Format: 2026-09-01T12:00:00.000-07:00 or ISO8601
        try:
            created_at = datetime.fromisoformat(snap.creation_timestamp)
        except ValueError:
            # Fallback for microsecond parsing
            clean_ts = snap.creation_timestamp.split(".")[0] + "+00:00"
            created_at = datetime.fromisoformat(clean_ts)

        age_days = (now - created_at).days
        disk_size_gb = snap.disk_size_gb or 0

        if age_days > retention_days:
            if dry_run:
                print(f"  🔍 [DRY-RUN] Would delete: {name} (Age: {age_days}d, Size: {disk_size_gb} GB)")
            else:
                try:
                    print(f"  🗑️  Deleting: {name} (Age: {age_days}d, Size: {disk_size_gb} GB)...")
                    operation = snapshot_client.delete(project=project_id, snapshot=name)
                    deleted_count += 1
                    total_freed_gb += disk_size_gb
                except GoogleAPICallError as e:
                    print(f"  ⚠️  Failed to delete {name}: {e}")
        else:
            retained_count += 1

    if dry_run:
        print(f"\n🔍 [DRY-RUN] Simulation finished. No snapshots were deleted.")
    else:
        print(f"\n🎉 Cleanup complete: {deleted_count} snapshots deleted (~{total_freed_gb} GB freed). {retained_count} snapshots retained.")


def main():
    parser = argparse.ArgumentParser(description="GKE Persistent Disk Snapshot FinOps Cleanup Tool")
    parser.add_argument(
        "--project-id",
        default=os.environ.get("GCP_PROJECT_ID", "msa-gcp-prod"),
        help="Google Cloud Project ID (Defaults to $GCP_PROJECT_ID or 'msa-gcp-prod')",
    )
    parser.add_argument("--retention-days", type=int, default=30, help="Maximum age in days before snapshot deletion (Default: 30)")
    parser.add_argument("--filter-prefix", default="", help="Optional snapshot name prefix filter (e.g. 'gke-')")
    parser.add_argument("--dry-run", action="store_true", help="Simulate snapshot cleanup without deleting")

    args = parser.parse_args()
    cleanup_snapshots(
        project_id=args.project_id,
        retention_days=args.retention_days,
        dry_run=args.dry_run,
        filter_prefix=args.filter_prefix,
    )


if __name__ == "__main__":
    main()
