spring:
  application:
    name: ${PRODUCTS_SERVICE_NAME:products-service}
  
  threads:
    virtual:
      enabled: true
  
  lifecycle:
    timeout-per-shutdown-phase: 30s
  
  cloud:
    vault:
      enabled: ${VAULT_ENABLED:false}
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PRODUCTS_SPRING_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5433/products_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      pool-name: ProductsHikariPool
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      leak-detection-threshold: 15000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # For prod ${HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        "[default_batch_fetch_size]": 25    # Optimizes relationships (categories, images, variants)
        "[order_inserts]": true             # Groups catalog inserts by batch
        "[order_updates]": true
      jdbc:
          '[batch_size]': 25

  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false # Avoid filling Redis with empty/null responses
      use-key-prefix: true
      key-prefix: "cache:products"

  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWT_URI:http://localhost:8181/realms/microservices-realm/protocol/openid-connect/certs}

server:
  port: ${PORT:8004}
  shutdown: graceful

springdoc:
  api-docs:
    version: openapi_3_0

logging:
  level:
    root: info
    "[org.springdoc.core.utils.SpringDocUtils]": error

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      base-path: /actuator/products
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when_authorized}
      probes:
        enabled: true
  # Enable only if you migrate from Prometheus scraper to OTLP Push for metrics:
  otlp:
    metrics:
      export:
        enabled: false
  #       url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    resource-attributes:
      "[service.name]": ${spring.application.name}
      "[service.version]": "1.0"
      "[deployment.environment]": ${ENVIRONMENT:dev}
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true