name: Notification Service CI/CD

on:
  push:
    branches: [ develop ]
    paths:
      - 'notification-service/**'
      - 'pom.xml'
  pull_request:
    branches: [ develop ]
    paths:
      - 'notification-service/**'
      - 'pom.xml'
  workflow_dispatch:

concurrency:
  group: notification-service-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/_service-ci-cd-template.yml
    with:
      service-name: notification-service
      service-type: spring-boot
      service-dir: notification-service
    secrets: inherit
