name: Products Service CI/CD

on:
  push:
    branches: [ develop ]
    paths:
      - 'products-service/**'
      - 'pom.xml'
      - '.github/workflows/_service-ci-cd-template.yml'
      - '.github/workflows/service-products.yml'
  pull_request:
    branches: [ develop ]
    paths:
      - 'products-service/**'
      - 'pom.xml'
      - '.github/workflows/_service-ci-cd-template.yml'
      - '.github/workflows/service-products.yml'
  workflow_dispatch:

concurrency:
  group: products-service-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/_service-ci-cd-template.yml
    with:
      service-name: products-service
      service-type: spring-boot
      service-dir: products-service
    secrets: inherit
